# Generated by Django 4.2.11 on 2026-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariocontacto',
            name='contactar_por_correo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulariocontacto',
            name='contactar_por_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
