# Generated by Django 4.2.11 on 2026-06-03 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_formulariocontacto_contactar_por_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='especificaciones',
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=255)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='productos.producto')),
            ],
            options={
                'db_table': 'especificacion',
            },
        ),
    ]
