# Generated by Django 4.2.11 on 2026-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_especificaciones_especificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaproducto',
            name='url_imagen',
            field=models.FileField(upload_to='galeria_productos/'),
        ),
    ]
