# Generated by Django 4.2.11 on 2026-06-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_galeriaproducto_url_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaproducto',
            name='url_imagen',
            field=models.FileField(upload_to='images/'),
        ),
    ]
