# Generated by Django 4.2.11 on 2026-06-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_galeriaproducto_url_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='ruta_destino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
